// <auto-generated />
namespace ConferenceFormSubmittal.DAL.CFSMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Prototype1_Feedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prototype1_Feedback));
        
        string IMigrationMetadata.Id
        {
            get { return "201803012100319_Prototype1_Feedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
