// <auto-generated />
namespace ConferenceFormSubmittal.DAL.CFSMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullableApplicationDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableApplicationDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201804102132441_NullableApplicationDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
